% : %.cpp
	$(CC) $(CPPFLAGS) -o $@ $< 
#CPPFLAGS =  -g   -fsanitize=address # -fsanitize=leak
#CPPFLAGS += -fopenmp  -O3 -march=native
#CPPFLAGS += -ffast-math    -ftree-vectorize  -fopt-info-vec-optimized=vector.txt
CC = FCCpx -Nclang
CPPFLAGS = -fopenmp  -Ofast 
CFLAGS += -Rpass=sve-loop-vectrizable

